### ISSUE TITLE
Numbers=OldStyle broken?

### ISSUE THREAD

**Issue by uhoefel** [latex3/fontspec#376] opened 2019-08-03 16:47 UTC
## Description
The following MWE produces only lining numbers for me, although it should produce OldStyle numerals.

## Check/indicate
- [ ] Relevant for XeTeX
- [x] Relevant for LuaTeX
- [x] Issue tracker has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate

## Minimal example demonstrating the issue
```
\listfiles
\documentclass{minimal}
\usepackage{fontspec}
\setmainfont{Libertinus Serif}[Numbers={OldStyle}]
\begin{document}
	1234567890
\end{document}
```
The listed files (should correspond to an up-to-date Miktex):
```
 *File List*
 minimal.cls    2001/05/25 Standard LaTeX minimal class
fontspec.sty    2019/03/15 v2.7c Font selection for XeLaTeX and LuaLaTeX
  xparse.sty    2019-05-28 L3 Experimental document command parser
   expl3.sty    2019-07-25 L3 programming layer (loader)
expl3-code.tex    2019-07-25 L3 programming layer
l3backend-pdfmode.def    2019-04-06 v L3 Experimental backend support: PDF mode
fontspec-luatex.sty    2019/03/15 v2.7c Font selection for XeLaTeX and LuaLaTeX
 fontenc.sty
   tuenc.def    2018/08/11 v2.0j Standard LaTeX file
fontspec.cfg
 ***********
```
Also breaks for (at least) Minion Pro.
However, switching to 
`\setmainfont{Libertinus Serif}[RawFeature=-lnum;+onum]`
enables the OldStyle numerals correctly.

**Comment by eg9** [comment] 2019-08-03 17:32
Your very same example outputs

<img width="123" alt="Screen Shot 2019-08-03 at 19 32 00 " src="https://user-images.githubusercontent.com/302839/62415154-6bcaaa80-b625-11e9-81a2-9caf3fa8b89d.png">

on my system. This is the file list:
```
 *File List*
 minimal.cls    2001/05/25 Standard LaTeX minimal class
fontspec.sty    2019/03/15 v2.7c Font selection for XeLaTeX and LuaLaTeX
  xparse.sty    2019-05-28 L3 Experimental document command parser
   expl3.sty    2019-07-25 L3 programming layer (loader) 
expl3-code.tex    2019-07-25 L3 programming layer 
l3backend-xdvipdfmx.def    2019-04-06 v L3 Experimental backend support: xdvipd
fmx
fontspec-xetex.sty    2019/03/15 v2.7c Font selection for XeLaTeX and LuaLaTeX
 fontenc.sty
   tuenc.def    2018/08/11 v2.0j Standard LaTeX file
fontspec.cfg
 ***********
```

**Comment by uhoefel** [comment] 2019-08-03 17:40
Using XeLaTeX or LuaLaTeX? I get the correct output using XeTeX as well, but not with LuaLaTeX.

**Comment by eg9** [comment] 2019-08-03 18:00
@uhoefel  With both engines. What's the output of `luaotfload-tool --version`?

**Comment by uhoefel** [comment] 2019-08-03 20:37
```
luaotfload-tool:
        Luaotfload font management and diagnostic utility.
        License: GNU GPL v2.0.
        Report problems to <https://github.com/lualatex/luaotfload/issues>

luaotfload-tool version: "2.98"
Luaotfload: "v2.98"
Revision: "aed2845ed28088243e91589a2707e3c0d8a12e50"
Lua interpreter: stock; version "Lua 5.3"
Luatex version: 1.10
Platform: type=windows name=windows
    +  machine: unknown
    + nodename: D
    +  release: build 18362
    +  sysname: Windows 10
    +  version: 10.00
Index: version=-1 created="2018-09-30 23:14:56" modified="2019-06-19 17:07:07"
```

**Comment by Kiwiengr** [comment] 2019-08-08 17:32
My LuaLaTeX configuration worked well for several months, then after the latest MiKTeX updates a few days ago, several things suddenly broke, including Erewhon oldstylenums, Erewhon fractions, and a loss of ligatures caused by the use of fontspec to enable fractions when needed (which most disastrously removed the overlap in -- and ---, let alone fi ff fl, etc.). Uhoefel's MWE gives same result for me: inline figures, whereas it should show oldstyle figures. I also get the same wrong result when I configure his MWE for Erewhon (and the \oldstylenums{} macro), see below. For the record, my file list is identical to his, and my luotfload is v. 2.98 (see below). The \oldstylenums{ } macro also broke with the MikTeX update, and had been working in hundreds of instances in my current book project, which now compiles in its entirety (1000 pages spread over seven part files) in LuaLaTeX (before I adopted LuaLaTeX, my up-to-date pdfLaTeX would fail with "insufficient memory" with more than one lstlistings environment not commented out, even though all listings of Mathematica code would work individually, but that is another issue, and nicely fixed by LuaLaTeX),   

*File List*
 minimal.cls    2001/05/25 Standard LaTeX minimal class
fontspec.sty    2019/03/15 v2.7c Font selection for XeLaTeX and LuaLaTeX
  xparse.sty    2019-05-28 L3 Experimental document command parser
   expl3.sty    2019-07-25 L3 programming layer (loader) 
expl3-code.tex    2019-07-25 L3 programming layer 
l3backend-pdfmode.def    2019-04-06 v L3 Experimental backend support: PDF mode
fontspec-luatex.sty    2019/03/15 v2.7c Font selection for XeLaTeX and LuaLaTeX
 fontenc.sty
   tuenc.def    2018/08/11 v2.0j Standard LaTeX file
fontspec.cfg
 ***********

Name: luaotfload
Date: Sat Jul 20 13:20:08 2019
Version: 2.98
Maintainer: PRAGMA ADE / ConTeXt Development Team
Size: 7.56 MiB

```
% MWE for oldstylenums problem
\listfiles
\documentclass{minimal}
\usepackage{fontspec}
\setmainfont{Erewhon}[Numbers={OldStyle}]
\begin{document}
	1234567890\\
	\oldstylenums{0123456789}
\end{document}
```

**The following is a MWE for the loss of ligatures (it is self-documenting):**
```
\listfiles
\documentclass{minimal}
\usepackage{fontspec}
\usepackage{booktabs}
\setmainfont{Erewhon}[UprightFont=Erewhon-Regular]
\setsansfont{TeXGyreHeros}[UprightFont=TeXGyreHeros-Regular]
\begin{document}
sans ff -- --- \\
\textsf{fi ff fl -- --- }\\
Fractions test: \fontspec[Fractions=On]{Erewhon}2/3 and 12345/67890 \textsf{ -- --- }\fontspec[Fractions=Off]{Erewhon}\\ % since last update, fractions broken
fi ff fl -- --- \\ % after the above fractions test line, ligatures no longer working in Erewhon
\textsf{sans ff -- --- }\\ % however, ligatures still working in sans
fi ff fl -- --- \\ % after the above fractions test line, ligatures no longer working in Erewhon
\textnormal{fi ff fl -- ---} \\ % ligatures are magically back
fi ff fl -- --- \\ % still gone in default text. I think you'd agree it would be a pain to have to specify textnormal { } for all default text
\end{document}
```

I have attached a pdf with its output. 
[Lost Ligatures MWE2.pdf](https://github.com/wspr/fontspec/files/3482971/Lost.Ligatures.MWE2.pdf)

**Comment by Kiwiengr** [comment] 2019-08-11 21:08
Also clobbered in the same MikTeX LuaLaTeX update: smallcaps
Here is an MWE:
```
% MWE2 for smallcaps problem
\listfiles
\documentclass{minimal}
\usepackage{fontspec}
\setmainfont{Erewhon}
\begin{document}
	\textsc{Good Night}
\end{document}
```
The output from this LuaLaTeX MWE is ordinary upper and lowercase text: Good Night 

My system is Windows10 home, 64-bit, 10.0.17763 Build 17763, 8 GiB physical memory.
My MikeTeX/LuaLaTeX differs from the one used in my previous two MWEs only as a result of a metalogox update yestersday.

A pdf of the smallcaps MWE log file is attached.
[MWE3 smallcaps.pdf](https://github.com/wspr/fontspec/files/3490448/MWE3.smallcaps.pdf)

**Comment by eg9** [comment] 2019-08-12 09:12
On my system (macOS) the `+smcp` feature is regularly added; it appears that it isn't on your system, which is what the missing font specification after
```
(fontspec) - 'small caps' (m/sc) with NFSS spec.:
```
says.

**Comment by Kiwiengr** [comment] 2019-08-12 18:06
eg9: I am very new at this, so I do not properly understand the implications of your comment re. your MacOS system vis-à-vis my Windows 10 MiKTeX system. The update that broke many things in my large LuaLaTeX writing project, performed by me on 8-5-2019, picked up all updates that were packaged by MiKTeX central after my previous update of 6-24-2019. As of yesterday, the MiKTeX Console reports that nothing is out-of-date. In any case, here is what I am finding (this seems to be just the tip of the proverbial iceberg) because prior to the update my 1200-page project in seven parts was compiling in its entirety with no errors. So many things broke that I suspect a common cause among many of them, probably in fontspec. Among the things that broke are the Erewhon \oldstylenums macro; the \textsc macro; \footnote{text} gives a missing } error, and if I respond with 's' to the console, the actual footnote is missing its number; Erewhon fractions (I am enabling them with the relatively long-winded \fontspec stuff, because LuaLaTeX is missing the convenience of the LaTeX \textfrac, etc., macros; and a loss of ligatures caused by the use of fontspec (usually to enable/disable fractions), which is most disastrously apparent in many 'random' portions of my manuscript missing the overlap in the dash ligatures, -- and ---, let alone fi ff fl, etc., reverting back to single letters. 

I have tried to make the following MWE produce self-documenting results, for easy reading.

```
% MWE for smallcaps and oldstylenums LuaLaTeX fontspec problem 
\listfiles
\documentclass{minimal}
\usepackage{fontspec}
\setmainfont{Erewhon}[Extension=.otf, UprightFont=*-Regular, RawFeature=+onum,] 
\begin{document}
\noindent
        My system's response is indicated with ( )\\
        Regular text: Good Night (normal text, OK)\\
        Old Style Nums: 1234567890 (old style nums, OK)\\
\fontspec[RawFeature=+smcp]{Erewhon}
	Using fontspec +smcp enables Small Caps: Good (small caps, OK)\\
	\textnormal{Textnormal macro works: Good Night (normal text, OK)}\\
	Small Caps is still enabled: Good (Small Caps, OK) \\
\fontspec[RawFeature=-smcp]{Erewhon}
        Using fontspec -smcp disables small caps: Good 1234567890 (no small caps, OK; ordinary nums, not OK)\\
        \textsc{And Also Noting Here That The textsc Macro Does Not Work} (normal text, not OK)\\ 
        Using fontspec for +/- smcp disables the global old style nums: 1234567890 (ordinary nums, not OK)\\
\fontspec[RawFeature=+onum]{Erewhon}
        Using fontspec +onum re-enables old style nums: 1234567890 (old style nums, OK)\\
        The oldstylenums macro nevertheless does not work: \oldstylenums{1234567890}\\
\fontspec[RawFeature=+smcp;+onum]{Erewhon}
        Using fontspec +smcp;+onum re-enables small caps and old style nums 1234567890
\end{document}
```
Please find my output in the attached pdf.
[Fontspec Oldstylenums and SmallCaps MWE.PDF](https://github.com/wspr/fontspec/files/3493653/Fontspec.Oldstylenums.and.SmallCaps.MWE.PDF)

**Comment by niknetniko** [comment] 2019-08-14 21:44
I'm having the same issue: almost all OpenType features (ligatures, old style numbers, etc.) no longer work. Perhaps this is related to https://github.com/wspr/fontspec/issues/364?

**Comment by wspr** [comment] 2019-08-15 00:42
@niknetniko — I think you're right; without looking further right now I am reasonably sure this is a luaotfload issue, not a fontspec one.

**Comment by Kiwiengr** [comment] 2019-08-15 15:53
Another MWE related to the small caps problem (adapted from a fontspec MWE by @John on tex.stackexchange.com)

```
% !TEX TS-program = LuaLaTeX
% !TEX encoding = UTF-8 Unicode  

\documentclass[11pt]{article}

\usepackage{fontspec} 

\setmainfont{texgyreheros}

\begin{document}
\noindent
Here is some {\bfseries\scshape Boldface SmallCaps} text (not OK)\\
Here is some {\bfseries\fontspec[RawFeature=+smcp]{texgyreheros}
Boldface SmallCaps {\fontspec[RawFeature=-smcp]{texgyreheros}}} text (RawFeature work-around) \\
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - \\
Here is some {\bfseries\uppercase{Boldface Uppercase}} text\\
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - \\
Here is some {\bfseries Boldface} text\\
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - \\
Here is some {\scshape SmallCaps} text (not OK)\\
Here is some {\fontspec[RawFeature=+smcp]{texgyreheros}
SmallCaps {\fontspec[RawFeature=-smcp]{texgyreheros}}} text (RawFeature work-around) \\
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - \\
Here is some \uppercase{Uppercase} text (OK)\\
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - \\
Here is some {Regular} text (OK)

\end{document}
```
Output attached as a pdf
[Stack Exchange - John - Fontspec 1.pdf](https://github.com/wspr/fontspec/files/3506237/Stack.Exchange.-.John.-.Fontspec.1.pdf)

**Comment by Kiwiengr** [comment] 2019-08-25 06:04
I updated 10:30 pm 8/24/2019 with miktex-luatek-bin-x64-2.9 Sat Aug 24, 13:11:14 2019 ver. 1.10.1, and about 29 other packages besides. A quick test shows shows most of not all of the things previously broken, as listed previously in #376 and comments, now work! I will do a more comprehensive test tomorrow. A big heartfelt thank you to all of the miktex-luatek wizards who fixed this! You know who you are. ;-)

**Comment by Kiwiengr** [comment] 2019-08-29 00:06
I have completed a more extensive test of the Lualatex updates. Things are working well enough that by not using certain relatively minor features (e.g., some of the ligatures), and ignoring certain others (e.g., that dashes sometimes render as - - - or - -), I can compile OK, and continue writing. This is a good place to be in compared to how it was a couple of weeks ago! The remaining problems are documented in the MWE file below, and the attached output. I have also attached the log file. 
In the MWE I have numbered the various commands/macros (1) thru (18) to make it more visible what does what, in order, and for easy reference.

I find it interesting that the dash ligatures are affected by \fontspec, but not the common ligatures like ff, fl, etc. 

On a slightly different note, I also find it interesting that my MWE (which relies entirely on the Windows 10 installation of the LibertinusSerif-Regular.otf font), when I add \usepackage{libertinus-otf} to the exisitng MWE, all dash ligatures correct overlap. I don’t know what side effects may or may not be caused by using this \usepackage, and is not the approach I want to use, my preference being to instead to install all desired fonts in Windows 10. Perhaps, however, it may offer some more clues about the buggy behavior of the default ligatures=TeX mode.    

Here is the MWE:
```
% !TEX TS-program = LuaLaTeX
% !TEX encoding = UTF-8 Unicode  

% -  -  -  -   L   U   A   L   A   T   E   X       M   W   E   -  -  -  -  -

% Exploration of bugs remaining after 24 August 2019 update.
% Author: Alastair Roxburgh (Kiwiengr)
% Date:  27 August 2019
\listfiles
\documentclass[11pt]{book}
\usepackage{fontspec} 
\usepackage[utf8]{luainputenc}
\usepackage{xcolor} % yellow for hi-lighter
\usepackage{soul}    % \hl{hi-lighted text}

\setmainfont{LibertinusSerif}[
    UprightFont=*-Regular,
%    ItalicFont=*-Italic,
    BoldFont=*-Bold, 
%    BoldItalicFont=*-BoldItalic, 
    SmallCapsFeatures={Letters=SmallCaps},
    Extension=.otf
    ]

\begin{document}
\noindent(1) Dash, std. ligatures OK: -- --- fb ff fh ffh fi ffi fj ffj fk ffk fl ffl ft fft ſh ſl ſs ſſ ſt \\
% Note:
%   Optional Historical (Historic) Ligatures:  ct, st \\
%   Optional Discretionary (Rare) Ligatures: Th, tt, tz, ck, ch \\
%   Optional Contextual (Contextual) Alternates: Qu Qv \\
(2) \fontspec[Fractions=On]{LibertinusSerif}Using \textbf{fontspec} to format fractions such as 4/15 \fontspec[Fractions=Off]{LibertinusSerif}
 makes dash ligatures \hl{NOT OK: -- ---}, but has no effect on the standard ligatures, which are still OK: e.g., ff fj\\
(3) Using \textbf{textnormal} restores dash ligatures OK, but only locally: \textnormal{-- ---}, while \\
(4) globally, dash ligatures are still \hl{NOT OK: -- ---}. Meanwhile, standard ligatures are nevertheless still OK: ff fj\\
\normalfont
(5) However, using \textbf{normalfont} makes dash ligatures OK globally again: -- --- ff fj\\

\vspace{-8pt}\noindent(6) The next three lines are a spot check of other things broken reported in github issue \#376, prior to Aug-24-2019 update, but are now OK:\\
(6.a)   \hspace{1em}Test footnote.\footnote{Footnotes would not compile (‘missing bracket’ problem), but are now OK.} \\ 
(6.b)  \hspace{1em}Oldstylenums macro now OK: \oldstylenums{0123456789}; inline numbers: 0123456789\\
(6.c)  \hspace{1em}\textsc{Small Caps Are Now OK}\\
After tests 6.a, 6.b, 6.c, dash ligatures, and the std ligatures are still OK: -- --- ff fj\\

\vspace{-8pt}\noindent(7) Now to shake out some bugs in \textbf{fontspec addfontfeature}:\\
\fontspec{LibertinusSerif}
\addfontfeature{{Ligatures=Historic}}{
(8) Adding in ‘LibertinusSerif Historic Ligatures’ is OK: wurtzite strict Qu Qv Th st ct tt tz firefly buff fjord Gauß}\\
\addfontfeature{{Ligatures=Rare}}{
(9) Adding in ‘LibertinusSerif Rare Ligatures’ is OK: wurtzite strict Qu Qv Th st ct tt tz firefly buff fjord Gauß}\\
\addfontfeature{{Ligatures=Contextual}}{
(10) Adding in ‘LibertinusSerif Contextual Ligatures’ \hl{does not work (note short tail on Qu, Qv)}: wurtzite strict Qu Qv Th st ct tt tz firefly buff fjord Gauß}\\
\fontspec{LibertinusSerif}
(11) Be that as it may, after the \textbf{fontspec addfontfeatures} stuff, the dash ligatures are \hl{NOT OK: -- ---}, but standard ligatures are still OK: ff fj\\
\normalfont
(12) Using \textbf{normalfont} makes dash ligatures and other standard ligatures OK globally again: -- --- ff fj \\
(13) Now try \textbf{fontspec’s RawFeature} on Discretionary and Contextual ligatures to prove that the correct long-tail ‘Q’ glyph is in fact in the LibertinusSerif font:\\
\fontspec[RawFeature=dlig]{LibertinusSerif} (14) RawFeature ‘Discretionary Ligatures ONLY’ (note that only Th tt tz are affected, which is OK): wurtzite strict Qu Qv Th st ct tt tz firefly buff fjord Gauß\\
\fontspec[RawFeature=calt]{LibertinusSerif} (15) RawFeature ‘Contextual Ligatures ONLY’ (note that other than the standard ligatures, only Qu Qv are affected which is OK): wurtzite strict Qu Qv Th st ct tt tz firefly buff fjord Gauß\\
\fontspec{LibertinusSerif}
(16) Again, \textbf{fontspec} has messed up dash ligatures, etc., \hl{NOT OK: -- ---}, but standard ligatures are still OK: ff fj\\
\normalfont
(17) \textbf{normalfont} makes dash ligatures and other standard ligatures OK globally again: -- --- ff fj\\
(18) And here are the rest of the std ligatures, all OK: ff fh ffh fi ffi fj ffj fk ffk fl ffl ft fft ſh ſl ſs ſſ ſt Qu Qv Th st ct tt tz strict firefly buff fjord Gauß\\
\end{document}
```

[MWE lulatex dash ligatures 2.PDF](https://github.com/wspr/fontspec/files/3553280/MWE.lulatex.dash.ligatures.2.PDF)

![Most recent updates](https://user-images.githubusercontent.com/50435086/63900483-80e0f200-c9b5-11e9-9bbb-b49a100648b9.png)

[MWE lulatex dash ligatures 2.log](https://github.com/wspr/fontspec/files/3553295/MWE.lulatex.dash.ligatures.2.log)

Here are some key version numbers from the package list in my MikTeX Console:
(also see list attached of recent updates in my MiKTeX)
*****miktex-luatex-bin-x64-2.9 
Sat Aug 24 13:11:44 2019 (Installed on my system 8/24/2019)
1.10.1
Taco Hoekwater and the LuaTeX Team
LuaTeX, Windows x64

*****luaotfload
Thu Aug 22 13:12:11 2019 (Installed on my system 8/24/2019)
2.991
PRAGMA ADE / ConTeXt Development Team
OpenType ‘loader’ for Plain TeX and LaTeX

*****fontspec
Fri Mar 15 14:11:54 2019 (Installed on my system 6/12/2019)
2.7c
Will Robertson
Advanced font selection in XeLaTeX and LuaLaTeX

And here is the file list from the log file (attached):
*File List*
    book.cls    2018/09/03 v1.4i Standard LaTeX document class
    bk11.clo    2018/09/03 v1.4i Standard LaTeX file (size option)
fontspec.sty    2019/03/15 v2.7c Font selection for XeLaTeX and LuaLaTeX
  xparse.sty    2019-05-28 L3 Experimental document command parser
   expl3.sty    2019-08-14 L3 programming layer (loader) 
expl3-code.tex    2019-08-14 L3 programming layer 
l3backend-pdfmode.def    2019-04-06 v L3 Experimental backend support: PDF mode
fontspec-luatex.sty    2019/03/15 v2.7c Font selection for XeLaTeX and LuaLaTeX
 fontenc.sty
   tuenc.def    2018/08/11 v2.0j Standard LaTeX file
fontspec.cfg
luainputenc.sty    2010/11/19 v0.973 inputenc package for LuaTeX
ifluatex.sty    2016/05/16 v1.4 Provides the ifluatex switch (HO)
 ifxetex.sty    2010/09/12 v0.6 Provides ifxetex conditional
luatexbase.sty    2015/10/04 v1.3 luatexbase interface to LuaTeX 
ctablestack.sty    2015/10/01 v1.0 Catcode table stable support
   lutf8.def    2010/05/10 v0.97 UTF-8 support for luainputenc
   t1enc.dfu    2018/10/05 v1.2f UTF-8 support for inputenc
  ot1enc.dfu    2018/10/05 v1.2f UTF-8 support for inputenc
  omsenc.dfu    2018/10/05 v1.2f UTF-8 support for inputenc
  xcolor.sty    2016/05/11 v2.12 LaTeX color extensions (UK)
   color.cfg    2016/01/02 v1.6 sample color configuration
  luatex.def    2018/01/08 v1.0l Graphics/color driver for luatex
    soul.sty    2003/11/17 v2.4 letterspacing/underlining (mf)
supp-pdf.mkii
 ***********

**Comment by wspr** [comment] 2020-02-10 03:26
Is this issue now resolved?

**Comment by Kiwiengr** [comment] 2020-02-10 20:07
Compared to August 2019, various issues touched on in this thread are resolved. A remaining issue, relevant to the LuaLaTeX context, relates to the use of fontspec to format fractions such as 4/15. On its face, such use of fontspec for on-the-fly font configuration breaks the dash en and em ligatures -- and --- (literally breaking them apart, resulting in gaps, like in this text). A workaround is detailed in a newly modified version of the MWE attached, GitHub ajr Test 2-10-2010.tex (also see pdf output). I have highlighted the errors caused by this remaining problem.
``
[GitHub ajr Test 2-10-2020.txt](https://github.com/wspr/fontspec/files/4182808/GitHub.ajr.Test.2-10-2020.txt)

``
![GitBub ajr Test 2-10-2020 output](https://user-images.githubusercontent.com/50435086/74185515-a5482800-4bfd-11ea-8211-deee62f10147.png)

**Comment by u-fischer** [comment] 2022-05-18 10:13
Closing as most (or all)  issues seem to be resolved in texlive 2022. Please open a new issue if something is still not working.

**Closed by u-fischer** 2022-05-18 10:13 UTC

**Comment by JimEBlevins** [comment] 2024-04-07 18:24
I stopped _oldstyle figures_ from rendering properly by misusing the  RawFeature command: 
> `RawFeature = {+case};` 

Here, the Unicode terminology (and RawFeature syntax) should be deprecated. 

The Unicode description is that this command "enforces case-sensitive forms", which sounds good. In fact, it forces numbers also to be upper-case (not lower case, etc.). 

The **fontspec** syntax is self-documenting, and should be preferred. 
> `Letters = Uppercase`

This information may help others, I hope, so I report it here in a _closed_ thread about old-style numbers, _with apologies_.
